# A configuration file is required for this project, like mysql/git configuration etc...
# Because some configurations involve security, they cannot be disclosed. You should create "config.yaml" under this project by yourself.
# All configuration information keys is in /tirelease/commons/configs/config.go in struct of ConfigYaml
# Config like this:
mysql_dsn: "root:your password@tcp(127.0.0.1:3306)/your_db_name?charset=utf8mb4&parseTime=True&loc=Local"
 
jenkins:
  username: "your jenkins account"
  password: "your password"
github:
  token: ""

restapisecret:
  admintoken: "1"
  tibuildtoken: "2"

cloudevent:
  endpoint: "http://localhost:8000"

tektonviewurl: "https://do.pingcap.net/tekton/#/namespaces/ee-cd/pipelineruns"
ocifileserverurl: "https://internal.do.pingcap.net:30443/dl/oci-file"
