apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: tiup-publisher
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: tiup-publisher
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
