// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProblemCaseRun is the predicate function for problemcaserun builders.
type ProblemCaseRun func(*sql.Selector)
