openapi: 3.0.3
info:
    title: Publish API
    description: Publish API
    contact:
        name: WuHui Zuo
        url: https://github.com/wuhuizuo
        email: wuhui.zuo@pingcap.com
    version: 1.0.0
servers:
    - url: http://0.0.0.0:80
paths:
    /tiup/publish-request:
        post:
            tags:
                - tiup
            summary: request-to-publish tiup
            operationId: tiup#request-to-publish
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestToPublishRequestBody'
                        example:
                            artifact_url: A facilis.
                            request_id: Sequi placeat blanditiis est iusto quia eum.
                            tiup-mirror: Sunt voluptates.
                            version: Rerum consectetur deleniti.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Distinctio voluptates voluptatem accusamus nisi omnis quia.
                                description: request track ids
                                example:
                                    - Voluptates possimus pariatur consequuntur itaque est dignissimos.
                                    - Atque amet optio et aliquam ut.
                                    - Nulla at error qui dolores et ipsa.
                                    - Rem nisi non.
                            example:
                                - Molestiae vitae ut commodi voluptatem consectetur.
                                - Magnam aut et labore.
    /tiup/publish-request/{request_id}:
        get:
            tags:
                - tiup
            summary: query-publishing-status tiup
            operationId: tiup#query-publishing-status
            parameters:
                - name: request_id
                  in: path
                  description: request track id
                  required: true
                  schema:
                    type: string
                    description: request track id
                    example: Facere maiores tenetur mollitia consequatur perferendis sint.
                  example: Nisi earum earum pariatur et animi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: request state
                                example: Necessitatibus officia distinctio officia voluptas laudantium iure.
                            example: Aperiam consequatur consequatur.
components:
    schemas:
        RequestToPublishRequestBody:
            type: object
            properties:
                artifact_url:
                    type: string
                    description: The full url of the pushed image, contain the tag part. It will parse the repo from it.
                    example: Voluptas ratione hic libero nisi.
                request_id:
                    type: string
                    description: The request id
                    example: Quibusdam nisi quam.
                tiup-mirror:
                    type: string
                    description: Staging is http://tiup.pingcap.net:8988, product is http://tiup.pingcap.net:8987.
                    default: http://tiup.pingcap.net:8988
                    example: Magni quia adipisci excepturi.
                version:
                    type: string
                    description: Force set the version. Default is the artifact version read from `org.opencontainers.image.version` of the manifest config.
                    example: Rerum voluptate accusantium optio.
            example:
                artifact_url: Atque vero in molestiae odit consequatur.
                request_id: Eos eveniet vero.
                tiup-mirror: Nemo rerum voluptas.
                version: Eum saepe nihil omnis dolorem eveniet.
            required:
                - artifact_url
                - tiup-mirror
tags:
    - name: tiup
      description: TiUP Publisher service
