apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatops-lark.fullname" . }}
  labels:
    {{- include "chatops-lark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chatops-lark.selectorLabels" . | nindent 4 }}
