// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProblemCaseRunsColumns holds the columns for the "problem_case_runs" table.
	ProblemCaseRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "repo", Type: field.TypeString},
		{Name: "branch", Type: field.TypeString},
		{Name: "suite_name", Type: field.TypeString},
		{Name: "case_name", Type: field.TypeString},
		{Name: "flaky", Type: field.TypeBool, Default: false},
		{Name: "timecost_ms", Type: field.TypeInt},
		{Name: "report_time", Type: field.TypeTime},
		{Name: "build_url", Type: field.TypeString, Size: 1024},
		{Name: "reason", Type: field.TypeString, Size: 32},
	}
	// ProblemCaseRunsTable holds the schema information for the "problem_case_runs" table.
	ProblemCaseRunsTable = &schema.Table{
		Name:       "problem_case_runs",
		Columns:    ProblemCaseRunsColumns,
		PrimaryKey: []*schema.Column{ProblemCaseRunsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProblemCaseRunsTable,
	}
)

func init() {
}
