CREATE TABLE IF NOT EXISTS ci_l1_builds (
  id BIGINT NOT NULL AUTO_INCREMENT,
  source_prow_row_id BIGINT NOT NULL,
  source_prow_job_id CHAR(36) NOT NULL,
  namespace VARCHAR(255) NOT NULL,
  job_name VARCHAR(255) NOT NULL,
  job_type VARCHAR(32) NOT NULL,
  state VARCHAR(32) NOT NULL,
  optional TINYINT(1) NOT NULL DEFAULT 0,
  report TINYINT(1) NOT NULL DEFAULT 0,
  org VARCHAR(63) NOT NULL,
  repo VARCHAR(63) NOT NULL,
  repo_full_name VARCHAR(127) NOT NULL,
  base_ref VARCHAR(255) NULL,
  pr_number BIGINT NULL,
  is_pr_build TINYINT(1) NOT NULL DEFAULT 0,
  context VARCHAR(255) NULL,
  url VARCHAR(1024) NOT NULL,
  normalized_build_url VARCHAR(1024) NULL,
  author VARCHAR(255) NULL,
  retest TINYINT(1) NULL,
  event_guid VARCHAR(255) NULL,
  build_id VARCHAR(64) NULL,
  pod_name VARCHAR(255) NULL,
  pending_time DATETIME NULL,
  start_time DATETIME NOT NULL,
  completion_time DATETIME NULL,
  queue_wait_seconds INT NULL,
  run_seconds INT NULL,
  total_seconds INT NULL,
  head_sha CHAR(40) NULL,
  target_branch VARCHAR(255) NULL,
  cloud_phase VARCHAR(16) NOT NULL DEFAULT 'IDC',
  build_system VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
  is_flaky TINYINT(1) NOT NULL DEFAULT 0,
  is_retry_loop TINYINT(1) NOT NULL DEFAULT 0,
  has_flaky_case_match TINYINT(1) NOT NULL DEFAULT 0,
  failure_category VARCHAR(32) NULL,
  failure_subcategory VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ci_l1_builds_source_prow_job_id (source_prow_job_id),
  KEY idx_ci_l1_builds_repo_time (repo_full_name, start_time),
  KEY idx_ci_l1_builds_repo_branch_time (repo_full_name, target_branch, start_time),
  KEY idx_ci_l1_builds_repo_pr_job_sha (repo_full_name, pr_number, job_name, head_sha, start_time),
  KEY idx_ci_l1_builds_pod_name_time (pod_name, start_time),
  KEY idx_ci_l1_builds_normalized_build_url (normalized_build_url(768))
);
