CREATE TABLE IF NOT EXISTS ci_l1_flaky_issues (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  repo VARCHAR(255) NOT NULL,
  issue_number BIGINT NOT NULL,
  issue_url VARCHAR(1024) NOT NULL,
  issue_title VARCHAR(512) NOT NULL,
  case_name VARCHAR(255) NOT NULL,
  issue_status VARCHAR(32) NOT NULL,
  issue_branch VARCHAR(255) NULL,
  branch_source VARCHAR(32) NOT NULL DEFAULT 'unknown',
  issue_created_at DATETIME NOT NULL,
  issue_updated_at DATETIME NOT NULL,
  issue_closed_at DATETIME NULL,
  last_reopened_at DATETIME NULL,
  reopen_count INT NOT NULL DEFAULT 0,
  source_ticket_id BIGINT NOT NULL,
  source_ticket_updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ci_l1_flaky_issues_repo_issue (repo, issue_number),
  KEY idx_ci_l1_flaky_issues_repo_branch_case (repo, issue_branch, case_name),
  KEY idx_ci_l1_flaky_issues_repo_status_updated (repo, issue_status, issue_updated_at),
  KEY idx_ci_l1_flaky_issues_repo_case_name (repo, case_name)
);
