CREATE TABLE IF NOT EXISTS ci_l1_pod_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  source_project VARCHAR(128) NOT NULL,
  cluster_name VARCHAR(128) NULL,
  location VARCHAR(64) NULL,
  namespace_name VARCHAR(255) NULL,
  pod_name VARCHAR(255) NULL,
  pod_uid VARCHAR(128) NULL,
  event_reason VARCHAR(128) NULL,
  event_type VARCHAR(64) NULL,
  event_message TEXT NULL,
  event_timestamp DATETIME NOT NULL,
  receive_timestamp DATETIME NOT NULL,
  first_timestamp DATETIME NULL,
  last_timestamp DATETIME NULL,
  reporting_component VARCHAR(128) NULL,
  reporting_instance VARCHAR(255) NULL,
  source_insert_id VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ci_l1_pod_events_source (source_project, source_insert_id),
  KEY idx_ci_l1_pod_events_identity_time (source_project, namespace_name, pod_uid, pod_name, event_timestamp),
  KEY idx_ci_l1_pod_events_namespace_time (namespace_name, event_timestamp),
  KEY idx_ci_l1_pod_events_pod_uid_time (pod_uid, event_timestamp),
  KEY idx_ci_l1_pod_events_pod_name_time (pod_name, event_timestamp),
  KEY idx_ci_l1_pod_events_reason_time (event_reason, event_timestamp)
);
