CREATE TABLE IF NOT EXISTS ci_l1_pod_lifecycle (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  source_project VARCHAR(128) NOT NULL,
  cluster_name VARCHAR(128) NULL,
  location VARCHAR(64) NULL,
  namespace_name VARCHAR(255) NULL,
  pod_name VARCHAR(255) NULL,
  pod_uid VARCHAR(128) NULL,
  build_system VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
  pod_labels_json TEXT NULL,
  pod_annotations_json TEXT NULL,
  metadata_observed_at DATETIME NULL,
  pod_created_at DATETIME NULL,
  pod_author VARCHAR(255) NULL,
  pod_org VARCHAR(255) NULL,
  pod_repo VARCHAR(255) NULL,
  jenkins_label VARCHAR(255) NULL,
  jenkins_label_digest VARCHAR(255) NULL,
  jenkins_controller VARCHAR(255) NULL,
  ci_job VARCHAR(255) NULL,
  source_prow_job_id VARCHAR(128) NULL,
  normalized_build_url VARCHAR(1024) NULL,
  repo_full_name VARCHAR(255) NULL,
  job_name VARCHAR(255) NULL,
  scheduled_at DATETIME NULL,
  first_pulling_at DATETIME NULL,
  first_pulled_at DATETIME NULL,
  first_created_at DATETIME NULL,
  first_started_at DATETIME NULL,
  last_failed_scheduling_at DATETIME NULL,
  failed_scheduling_count INT NOT NULL DEFAULT 0,
  last_event_at DATETIME NULL,
  schedule_to_started_seconds INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ci_l1_pod_lifecycle_identity (source_project, namespace_name, pod_uid, pod_name),
  KEY idx_ci_l1_pod_lifecycle_pod_name (pod_name),
  KEY idx_ci_l1_pod_lifecycle_build_system_time (build_system, scheduled_at),
  KEY idx_ci_l1_pod_lifecycle_build_key_time (source_prow_job_id, scheduled_at),
  KEY idx_ci_l1_pod_lifecycle_normalized_build_url (normalized_build_url(768)),
  KEY idx_ci_l1_pod_lifecycle_job_time (job_name, scheduled_at),
  KEY idx_ci_l1_pod_lifecycle_repo_time (repo_full_name, scheduled_at)
);
