apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mac-builder-operator.fullname" . }}
  labels:
    {{- include "mac-builder-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mac-builder-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mac-builder-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mac-builder-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            {{- if .Values.controller.agent }}
            - --enable-agent
            {{- with .Values.agent.workerName }}
            - --worker-name={{ . }}
            {{- end }}
            {{- with .Values.agent.workerArch }}
            - --worker-arch={{ . }}
            {{- end }}
            - --build-timeout={{ .Values.agent.buildTimeout }}
            - --build-poll-interval={{ .Values.agent.buildPollInterval }}
            - --artifacts-repo-url={{ .Values.artifactsRepo.url }}
            - --artifacts-repo-revision={{ .Values.artifactsRepo.revision }}
            - --artifacts-repo-commit={{ .Values.artifactsRepo.commit }}
            {{- end }}
            {{- if .Values.controller.gc }}
            - --enable-gc
            {{- end }}
            {{- if .Values.controller.customRun }}
            - --enable-customrun
            - --macbuild-namespace={{ include "mac-builder-operator.macBuildNamespace" . }}
            - --customrun-poll-interval={{ .Values.customRun.pollInterval }}
            {{- end }}
            {{- if or .Values.controller.gc .Values.controller.customRun }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address=:8081
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:8443
            - --metrics-secure={{ .Values.metrics.secure }}
            {{- end }}
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: https
              containerPort: 8443
              protocol: TCP
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
