# knowledge-base-mcp/src/vector_search/docker-compose.yml
version: '3.8'

services:
  backend:
    image: purelind/tiassistant-vector-search-backend:latest
    container_name: vector_search_backend
    ports:
      - "5000:5000" 
    volumes:
      - ./ca.pem:/app/ca.pem
    command: ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:5000", "--timeout", "120", "vector_search.app:app"]
    restart: unless-stopped

  frontend:
    image: purelind/tiassistant-vector-search-frontend:latest
    container_name: vector_search_frontend
    ports:
      - "3000:3000" 
    environment:
      # Tell Next.js where the backend API is running (service name 'backend' on port 5000)
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000
    depends_on:
      - backend 
    restart: unless-stopped
