// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/artifact/sync-image": {
            "post": {
                "description": "sync",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifact"
                ],
                "summary": "sync hotfix image to dockerhub",
                "parameters": [
                    {
                        "description": "image sync to public, only hotfix is accepted right now",
                        "name": "ImageSyncRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ImageSyncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ImageSyncRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/devbuilds": {
            "get": {
                "description": "list devbuild",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devbuild"
                ],
                "summary": "list devbuild",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "the size limit of items",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "the start position of items",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "filter hotfix",
                        "name": "hotfix",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter created by",
                        "name": "createdBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.DevBuild"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "create and trigger devbuild",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devbuild"
                ],
                "summary": "create and trigger devbuild",
                "parameters": [
                    {
                        "description": "build to create, only spec filed is required, others are ignored",
                        "name": "DevBuild",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.DevBuild"
                        }
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "dry run",
                        "name": "dryrun",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.DevBuild"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/devbuilds/{id}": {
            "get": {
                "description": "get devbuild",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devbuild"
                ],
                "summary": "get devbuild",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of build",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "whether sync with jenkins",
                        "name": "sync",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.DevBuild"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "update the status field of a build",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devbuild"
                ],
                "summary": "update devbuild status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of build",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "build to update",
                        "name": "DevBuild",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.DevBuild"
                        }
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "dry run",
                        "name": "dryrun",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.DevBuild"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/devbuilds/{id}/rerun": {
            "post": {
                "description": "rerun devbuild",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devbuild"
                ],
                "summary": "rerun devbuild",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of build",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "dry run",
                        "name": "dryrun",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.DevBuild"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "service.BinArtifact": {
            "type": "object",
            "properties": {
                "component": {
                    "type": "string"
                },
                "ociFile": {
                    "$ref": "#/definitions/service.OciFile"
                },
                "platform": {
                    "type": "string"
                },
                "sha256OciFile": {
                    "$ref": "#/definitions/service.OciFile"
                },
                "sha256URL": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "service.BranchCreateReq": {
            "type": "object",
            "properties": {
                "baseVersion": {
                    "type": "string"
                },
                "prod": {
                    "type": "string"
                }
            }
        },
        "service.BranchCreateResp": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "branchURL": {
                    "type": "string"
                }
            }
        },
        "service.BuildReport": {
            "type": "object",
            "properties": {
                "binaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.BinArtifact"
                    }
                },
                "gitHash": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ImageArtifact"
                    }
                },
                "pluginGitHash": {
                    "type": "string"
                },
                "printedVersion": {
                    "type": "string"
                }
            }
        },
        "service.DevBuild": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "meta": {
                    "$ref": "#/definitions/service.DevBuildMeta"
                },
                "spec": {
                    "$ref": "#/definitions/service.DevBuildSpec"
                },
                "status": {
                    "$ref": "#/definitions/service.DevBuildStatus"
                }
            }
        },
        "service.DevBuildMeta": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "service.DevBuildSpec": {
            "type": "object",
            "properties": {
                "buildEnv": {
                    "type": "string"
                },
                "builderImg": {
                    "type": "string"
                },
                "edition": {
                    "type": "string"
                },
                "features": {
                    "type": "string"
                },
                "gitHash": {
                    "type": "string"
                },
                "gitRef": {
                    "type": "string"
                },
                "githubRepo": {
                    "type": "string"
                },
                "isHotfix": {
                    "type": "boolean"
                },
                "isPushGCR": {
                    "type": "boolean"
                },
                "pipelineEngine": {
                    "type": "string"
                },
                "platform": {
                    "description": "\"linux\", \"darwin\" or \"linux/amd64\" or \"linux/arm64\" or \"darwin/amd64\" or \"darwin/arm64\" or empty for all platforms.",
                    "type": "string"
                },
                "pluginGitRef": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "productBaseImg": {
                    "type": "string"
                },
                "productDockerfile": {
                    "type": "string"
                },
                "targetImg": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "service.DevBuildStatus": {
            "type": "object",
            "properties": {
                "buildReport": {
                    "$ref": "#/definitions/service.BuildReport"
                },
                "errMsg": {
                    "type": "string"
                },
                "pipelineBuildID": {
                    "type": "integer"
                },
                "pipelineEndAt": {
                    "type": "string"
                },
                "pipelineStartAt": {
                    "type": "string"
                },
                "pipelineViewURL": {
                    "type": "string"
                },
                "pipelineViewURLs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "tektonStatus": {
                    "$ref": "#/definitions/service.TektonStatus"
                }
            }
        },
        "service.ImageArtifact": {
            "type": "object",
            "properties": {
                "internal_url": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "service.ImageSyncRequest": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "service.OciArtifact": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "repo": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "service.OciFile": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "service.TagCreateReq": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "prod": {
                    "type": "string"
                }
            }
        },
        "service.TagCreateResp": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string"
                },
                "tagURL": {
                    "type": "string"
                }
            }
        },
        "service.TektonPipeline": {
            "type": "object",
            "properties": {
                "endAt": {
                    "type": "string"
                },
                "gitHash": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ImageArtifact"
                    }
                },
                "name": {
                    "type": "string"
                },
                "ociArtifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.OciArtifact"
                    }
                },
                "platform": {
                    "type": "string"
                },
                "startAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "service.TektonStatus": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TektonPipeline"
                    }
                }
            }
        },
        "service.TidbXHotfixTagCreateReq": {
            "type": "object",
            "required": [
                "author",
                "repo"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "branch": {
                    "type": "string"
                },
                "commit": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                }
            }
        },
        "service.TidbXHotfixTagCreateResp": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
