from __future__ import annotations

ERROR_CLASSIFICATION_GUIDANCE = """Decision guidance:
- Classify the semantic root cause, not secondary Jenkins/pod noise.
- If a real test/build failure appears before Jenkins remoting, agent disconnect, post-step, or pod-event noise, prefer the test/build category.
- Failed pipeline node log excerpts are higher-signal than the root console tail when matrix branches are interrupted.
- Stage names or wrapper steps such as "prepare depends", "build", or generic pipeline/config steps are weak hints; classify the underlying compiler, dependency, test, or merge evidence instead.
- In this autoscaled CI environment, FailedScheduling/Unschedulable/Insufficient resources/taints/PVC waits during pod Pending are normal scheduling pressure, not an error by themselves.
- Only classify Kubernetes as INFRA when there is final pod/container failure evidence such as TerminationByKubelet, OOMKilled, or Evicted.
- Do not classify K8S_MEMORY_EVICTION from partial memory-usage snippets alone; require final kubelet pod-failure evidence such as `Pod [Failed][TerminationByKubelet] The node was low on resource: memory`.
- Container termination reason OOMKilled is INFRA/OOMKILLED, even when Jenkins later reports a matrix branch failure or agent disconnect.
- Use job names as strong hints for test families: ghpr/pull unit/mysql jobs are UT, integration/realcluster/lightning/br/dm integration jobs are IT.
- ghpr_check2 test-failure evidence should usually stay in the UT family because that job behaves like a unit-style mixed check job; do not move it to IT unless the failing evidence is explicitly integration-specific.
- ghpr_check2 timeout evidence can move to IT/TIMEOUT when the failing branch is explicitly integration-specific, for example `run_real_tikv_tests.sh ...` or `integrationtest_with_tikv.sh ...`, even though the outer job name is ghpr_check2.
- ghpr_check2 realtikv/integration failure evidence such as `//tests/realtikvtest/... FAILED`, `Test output for //tests/realtikvtest/...`, or PD `NOT_BOOTSTRAPPED` errors inside `run_real_tikv_tests.sh` or `integrationtest_with_tikv.sh` branches should be IT/TEST_FAILURE, not UT/TEST_FAILURE.
- pull/release `pull_check2` jobs with explicit `realtikv` target failures such as `//tests/realtikvtest/... FAILED`, `Test output for //tests/realtikvtest/...`, or PD `NOT_BOOTSTRAPPED` errors should also be IT/TEST_FAILURE rather than OTHERS/UNCLASSIFIED.
- In realcluster or ghpr_check2 mixed logs, explicit add-index/import-into duplicate-key evidence such as `[kv:1062]Duplicate entry`, `ErrFoundDuplicateKey`, or `run add index job failed, convert job to rollback` should be IT/TEST_FAILURE even if the same console earlier contains Bazel dependency download failures.
- Go compiler errors such as "undefined:" or "has no field or method" are BUILD/COMPILE, even when they appear inside Bazel or wrapper output.
- Bazel/unit summaries such as "FAILED TO BUILD", "fails to build", or "0 failing out of 0 test cases" point to an upstream build problem, not a UT test failure by themselves.
- Failpoint rewrite/parser errors such as "Rewrite error ... expected declaration/statement, found '<<'" are BUILD/COMPILE.
- Raw merge-conflict markers that leak into source after pre-merge, such as `malformed module path "<<<<<<<"` or `syntax error: unexpected <<`, are OTHERS/CODE_CONFLICT rather than BUILD/COMPILE.
- Missing internal TiDB package imports such as `no required module provides package github.com/pingcap/tidb/...` are BUILD/COMPILE, while generic module hygiene failures such as `go mod tidy` or strict-deps drift stay BUILD/DEPENDENCY.
- Dependency hygiene failures such as "updates to go.mod needed", "missing strict dependencies", "No dependencies were provided", imports/deps mismatch, or `invalid version: unknown revision` are BUILD/DEPENDENCY.
- Support-repo checkout failures that log `tidb-test=<40-hex-sha>` and then `Couldn't find any revision to build` are BUILD/PIPELINE_CONFIG; treat them as CI checkout/refspec logic failures rather than INFRA/GIT noise.
- Support-repo checkout failures that log `computeBranchFromPR component: tidb-test`, warn that the `tidb-test` PR base branch must match the `tidb` PR base branch, and then fail with `fatal: couldn't find remote ref refs/heads/...` are BUILD/PIPELINE_CONFIG; treat them as CI checkout/refspec logic failures rather than INFRA/GIT noise.
- Direct main-repo checkout failures such as `fatal: couldn't find remote ref refs/pull/<num>/head` are INFRA/GIT, not BUILD/PIPELINE_CONFIG; they often reflect a transient GitHub pull-ref visibility issue, and later matrix or agent noise should be ignored.
- Nogo or build-time static-analysis validation failures such as "Validating nogo output" or "Running nogo on //... failed" are BUILD/FORMAT_CHECK, including ghpr_build, ghpr_check2, pull_build_next_gen, and pull_unit_test jobs; do not leave them in BUILD/PIPELINE_CONFIG or move them to BUILD/COMPILE.
- This also applies when those `nogo` / `Validating nogo output` failures happen inside integration-family wrappers such as `pull_integration_realcluster_test_next_gen`; they are still BUILD/FORMAT_CHECK.
- Repository/archive download failures such as "Error downloading", "Error computing the main repository mapping", download 404/429/502/503/504, or read-timeout while fetching Bazel/GitHub dependencies are INFRA/EXTERNAL_DEP even if matrix branches later show test interruptions.
- Bazel remote-cache throttling evidence such as `Remote Cache: 429 Too Many Requests`, `Failed to fetch blobs because of a remote cache error`, or GCS `SlowDown ... exceeded your bucket's IO capacity` is INFRA/NETWORK rather than INFRA/EXTERNAL_DEP.
- Bazel server failures such as `Server terminated abruptly (error code: 14, error message: 'Socket closed')` are INFRA/NETWORK when there is no earlier stronger build/test root cause.
- For integration job families, Jenkins/test wrapper timeout evidence such as "Timeout has been exceeded" is IT/TIMEOUT, not INFRA/NETWORK.
- BR integration matrix TEST_GROUP failures are IT/TEST_FAILURE, even if the failed case logs local 127.0.0.1 PD/TiKV connection-refused or timeout symptoms.
- merged integration matrix failures should usually stay in IT/TEST_FAILURE when the failed branch also shows concrete product/test evidence such as `TEST FAILED`, duplicate-key exceptions, JDBC assertion failures, BR store-backup failures, or local service connection-refused inside the test workload.
- `merged_integration_mysql_test` query/result mismatches such as `query succeeded, but expected error(s)!` or `query failed with non expected error(s)!` are IT/TEST_FAILURE.
- BR restore compatibility failures such as "ErrRestoreNotFreshCluster", "ErrRestoreIncompatibleSys", "missing column in cluster data", or "incompatible column, table:" are IT/TEST_FAILURE, even if later console tail shows scatter warnings or Jenkins remoting noise.
- For `pull_cdc_storage_integration_light`, matrix `TEST_GROUP` failures with `TEST FAILED`, `check diff failed`, `check data failed`, or `run task failed` are IT/TEST_FAILURE, even if the same build also had transient Pending/PVC scheduling noise.
- For `pull_cdc_storage_integration_heavy_next_gen`, matrix/data-check failures such as `check diff failed`, `ErrTableIsNotFounded`, or `ErrMaintainerNotFounded` are IT/TEST_FAILURE.
- For `ghpr_check`, `make ... integrationtest` failures with plan diff or integration output mismatch evidence are IT/TEST_FAILURE rather than INFRA/NETWORK.
- Kubelet final pod failures such as `TerminationByKubelet` with `imminent node shutdown` are INFRA/SPOT_PREEMPTED when pod-side evidence shows the workload was running on a `-spot-` node; otherwise classify them as INFRA/K8S_NODE_SHUTDOWN. Explicit `Evicted` pod/container failures, especially storage or `ephemeral-storage` pressure, are INFRA/K8S_STORAGE_EVICTED. These Kubernetes root causes should beat later Jenkins remoting or agent-offline noise.
- Jenkins Groovy/runtime/cache/websocket/controller persistence errors are INFRA subcategories, not product BUILD failures.
- If a log first shows checkout interruption or agent-loss evidence such as `ERROR: Checkout failed`, `java.lang.InterruptedException`, or `AgentOfflineException: Unable to create live FilePath`, and only later shows `groovy.lang.MissingPropertyException: No such property: source`, prefer INFRA/JENKINS_AGENT_OFFLINE over INFRA/JENKINS_GROOVY.
- Agent disconnect/remoting failures such as `Timeout waiting for agent to come back`, `AgentOfflineException`, or `was marked offline: Connection was broken` are INFRA/JENKINS_AGENT_OFFLINE when there is no earlier stronger root cause.
- Disk-full evidence such as "No space left on device" is INFRA/DISK_FULL even when it appears while Jenkins saves pipeline state.
- TiDB ingest environment errors such as `Error 8256 (HY000): Check ingest environment failed: no enough space in /tmp/tidb/...` are also INFRA/DISK_FULL.
- Prow superseded aborts are OTHERS/SUPERSEDED_BY_NEWER_BUILD when Prow marks the job aborted because a newer same-PR same-job version is running, or when an admin-abort log has same-PR same-job newer different-SHA build evidence; this overrides downstream noise.
- Admin aborts are OTHERS/ABORT_BY_ADMIN and override downstream matrix, network, or interrupted-process symptoms.
- Merge conflicts such as "CONFLICT (content)" or "Automatic merge failed" are OTHERS/CODE_CONFLICT, because they are neither infra nor product test/build quality failures.
- Return the default classification when the log tail is weak or only contains ambiguous downstream symptoms."""
