store:
  driver: sqlite3
  dsn: file:ent?mode=memory&cache=shared&_fk=1
lark:
  app_id: cli_12345678
  app_secret: s123456789
tibuild:
  result_sink_url: http://tibuild.event.url:8080 # url of tibuild events listener.
  trigger_sink_url: http://el-xxx.tekton.url:8080 # url of tekton event listener.
tekton:
  dashboard_base_url: https://tekton.local.com/dashboard-path
  notifications:
    - event_type: ".*"
      receivers: [all-level-receiver]
    - event_type: dev.tekton.event.pipelinerun.started.v1
      receivers: [started-receiver]
    - event_type: dev.tekton.event.pipelinerun.running.v1
      receivers: [running-receiver]
    - event_type: dev.tekton.event.pipelinerun.successful.v1
      receivers: [successful-receiver]
    - event_type: dev.tekton.event.pipelinerun.failed.v1
      event_subject_reg: ^xxx-from-.*
      receivers: [failure-receiver]
kafka:
  brokers:
    - broker1:9092
  client_id: cloudevents-server
  # authentication:
  #   mechanism: SCRAM-SHA-256
  #   user: username
  #   password: password
  producer:
    topic_mapping: {}
    default_topic: test-topic
  consumer:
    group_id: consumer-group-1
    topic_mapping:
      '*': test-topic
    dead_letter_topic: test-topic-dead-letter
