swagger: "2.0"
info:
    title: Download OCI artifacts Service
    description: Service for downloading files from OCI artifact
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /healthz:
        get:
            tags:
                - health
            summary: healthz health
            operationId: health#healthz
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
            schemes:
                - http
    /livez:
        get:
            tags:
                - health
            summary: livez health
            operationId: health#livez
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
            schemes:
                - http
    /oci-file/{repository}:
        get:
            tags:
                - oci
            summary: download-file oci
            operationId: oci#download-file
            produces:
                - application/octet-stream
            parameters:
                - name: file
                  in: query
                  description: file name in OCI artifact
                  required: true
                  type: string
                - name: tag
                  in: query
                  description: OCI artifact tag
                  required: true
                  type: string
                - name: repository
                  in: path
                  description: OCI artifact repository
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    headers:
                        Content-Disposition:
                            description: Content-Disposition header for downloading
                            type: string
                        Content-Length:
                            description: Length is the downloaded content length in bytes.
                            type: int64
            schemes:
                - http
    /oci-files/{repository}:
        get:
            tags:
                - oci
            summary: list-files oci
            operationId: oci#list-files
            parameters:
                - name: tag
                  in: query
                  description: OCI artifact tag
                  required: true
                  type: string
                - name: repository
                  in: path
                  description: OCI artifact repository
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Et aut labore veniam et maiores qui.
            schemes:
                - http
    /s3-obj/{bucket}/{key}:
        get:
            tags:
                - ks3
            summary: download-object ks3
            operationId: ks3#download-object
            produces:
                - application/octet-stream
            parameters:
                - name: bucket
                  in: path
                  description: bucket name
                  required: true
                  type: string
                - name: key
                  in: path
                  description: object key
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    headers:
                        Content-Disposition:
                            description: Content-Disposition header for downloading
                            type: string
                        Content-Length:
                            description: Length is the downloaded content length in bytes.
                            type: int64
            schemes:
                - http
