apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: publisher
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: publisher
      ko:
        fromImage: gcr.io/distroless/static
        main: ./cmd/publisher
        dependencies:
          paths:
            - "**/*.go"
            - "go.mod"
            - "go.sum"
          ignore:
            - cmd/publisher-cli
            - cmd/worker
        flags:
          - -trimpath # Ko build flags (optional)
          - -v
        labels:
          org.opencontainers.image.title: PingCAP Publisher Server
          org.opencontainers.image.licenses: MIT License
          org.opencontainers.image.source: https://github.com/PingCAP-QE/ee-apps
          org.opencontainers.image.url: https://github.com/PingCAP-QE/ee-apps/tree/main/publisher

    - image: publisher-worker
      ko:
        fromImage: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.26-7-geb77a69
        main: ./cmd/worker
        dependencies:
          paths:
            - "**/*.go"
            - go.mod
            - go.sum
          ignore:
            - cmd/publisher-cli
            - cmd/publisher
        flags:
          - -trimpath # Ko build flags (optional)
          - -v
        labels:
          org.opencontainers.image.title: PingCAP Publisher Worker
          org.opencontainers.image.licenses: MIT License
          org.opencontainers.image.source: https://github.com/PingCAP-QE/ee-apps
          org.opencontainers.image.url: https://github.com/PingCAP-QE/ee-apps/tree/main/publisher

    - image: publisher-cli
      ko:
        fromImage: ghcr.io/pingcap-qe/cd/utils/release:v2025.10.26-7-geb77a69
        main: ./cmd/publisher-cli
        dependencies:
          paths:
            - go.mod
            - go.sum
            - cmd/publisher-cli
            - internal/service/gen
        flags:
          - -trimpath # Ko build flags (optional)
          - -v
        labels:
          org.opencontainers.image.title: PingCAP Publisher CLI
          org.opencontainers.image.licenses: MIT License
          org.opencontainers.image.source: https://github.com/PingCAP-QE/ee-apps
          org.opencontainers.image.url: https://github.com/PingCAP-QE/ee-apps/tree/main/publisher
