kafka:
  brokers:
    - example-bootstrap.kafka:9092
  topic: example-topic
  consumer_group: example-group
options:
  mirror_url: http://tiup.mirror.site
  lark_webhook_url: https://feishu.custom-bot-webhook # create and copy the url then paste here.
  nightly_interval: 1h