// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/PingCAP-QE/ee-apps/cloudevents-server/ent/runtime.go

const (
	Version = "v0.14.2-0.20241102145616-365b49817603"           // Version of ent codegen.
	Sum     = "h1:mdW4xCZP/KQOGI8xMn1+ARzlucpmG44ux9ZqwYbYpIg=" // Sum of ent codegen.
)
