apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cloudevents-server
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: cloudevents-server
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
manifests:
  rawYaml:
    - deployments/k8s-dev.yaml
portForward:
  - resourceType: service
    resourceName: cloudevents-server
    port: 80
deploy:
  kubectl: {}
