apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cloudevents-server
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: ghcr.io/pingcap-qe/ee-apps/cloudevents-server
      ko:
        fromImage: cgr.dev/chainguard/bash:latest
        env:
          - GOPROXY={{.GOPROXY}}
        labels:
          org.opencontainers.image.licenses: MIT
          org.opencontainers.image.source: https://github.com/PingCAP-QE/ee-apps
manifests:
  rawYaml:
    - deployments/k8s-dev.yaml
portForward:
  - resourceType: service
    resourceName: cloudevents-server
    port: 8080
deploy:
  kubectl: {}
profiles:
  - name: dev
    patches:
      - op: add
        path: /build/artifacts/0/ko/flags
        value:
          - --tags=sqlite3
